version: "3"
services:
  web:
    image: "ghcr.io/joshghent/openemote:latest"
    restart: always
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - traefik-net
    labels:
      - traefik.enable=true
      - traefik.http.routers.openemote.rule=Host(`openemote.joshghent.com`)
      - traefik.http.routers.openemote.entrypoints=web
  redis:
    image: "redis:alpine"
    restart: always
    networks:
      - traefik-net
    command: redis-server --requirepass ${REDIS_PASSWORD}
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
  traefik:
    image: traefik:v2.4
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
    ports:
      - 80:80
      - 8080:8080
    networks:
      - traefik-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

networks:
  traefik-net:

volumes:
  redis-data:
